const fs = require('fs');
const filePath = 'src/content/week-06/day-27.ts';
let content = fs.readFileSync(filePath, 'utf8');
const lines = content.split('\n');
let theoryStarts = [], theoryEnds = [];
for (let i = 0; i < lines.length; i++) {
  if (lines[i].includes('theory: `') && !lines[i].trim().startsWith('//')) theoryStarts.push(i);
}
for (let i = 0; i < lines.length; i++) {
  if (lines[i].trim() === '`,' && theoryStarts.some(s => i > s)) theoryEnds.push(i);
}
const physStart = theoryStarts[0], physEnd = theoryEnds[0];
const rusStart = theoryStarts[1], rusEnd = theoryEnds[1];
console.log('Physics:', physStart+1, '-', physEnd+1, 'Russian:', rusStart+1, '-', rusEnd+1);

const newPhys = [
'      theory: `## Последовательное и параллельное соединение',
'',
'В реальных цепях компоненты соединяются по-разному. От типа соединения зависят сила тока, напряжение и сопротивление.',
'',
'---',
'',
'### Последовательное соединение',
'',
'<div class="theory-definition">',
'<strong>Последовательное:</strong> проводники — друг за другом, без разветвлений.',
'</div>',
'',
'<strong>Свойства:</strong>',
'1. $I = I_1 = I_2 = ... = I_n$ (ток одинаков)',
'2. $U = U_1 + U_2 + ... + U_n$ (напряжение суммируется)',
'3. $R = R_1 + R_2 + ... + R_n$ (сопротивление суммируется)',
'',
'<div class="theory-example">',
'<strong>Задача:</strong> Резисторы 2 Ом и 3 Ом последовательно. Найдите общее сопротивление.',
'<p><strong>Решение:</strong> $R = 2 + 3 = 5$ Ом.</p>',
'</div>',
'',
'<div class="theory-example">',
'<strong>Задача:</strong> К источнику 24 В подключены последовательно 2 Ом и 6 Ом. Найдите ток и напряжение на каждом.',
'<p><strong>Решение:</strong> $R = 2+6 = 8$ Ом. $I = 24/8 = 3$ А.</p>',
'<p>$U_1 = 3 \cdot 2 = 6$ В. $U_2 = 3 \cdot 6 = 18$ В.</p>',
'</div>',
'',
'---',
'',
'### Параллельное соединение',
'',
'<div class="theory-definition">',
'<strong>Параллельное:</strong> начала соединены вместе, концы — вместе. Ток разветвляется.',
'</div>',
'',
'<strong>Свойства:</strong>',
'1. $U = U_1 = U_2 = ... = U_n$ (напряжение одинаково)',
'2. $I = I_1 + I_2 + ... + I_n$ (ток суммируется)',
'3. $\frac{1}{R} = \frac{1}{R_1} + \frac{1}{R_2} + ... + \frac{1}{R_n}$',
'',
'<strong>Для двух:</strong> $R = \frac{R_1 \cdot R_2}{R_1 + R_2}$',
'',
'<div class="theory-example">',
'<strong>Задача:</strong> Резисторы 3 Ом и 6 Ом параллельно. Найдите общее сопротивление.',
'<p><strong>Решение:</strong> $R = \frac{3 \cdot 6}{3+6} = \frac{18}{9} = 2$ Ом.</p>',
'</div>',
'',
'<div class="theory-warning">',
'<strong>Важно:</strong> Общее сопротивление параллельного соединения всегда <strong>меньше</strong> наименьшего из сопротивлений!',
'</div>',
'',
'---',
'',
'### Смешанное соединение',
'',
'<p>Содержит последовательные и параллельные участки. Расчёт поэтапно:</p>',
'<ol>',
'<li>Найдите сопротивление параллельных участков.</li>',
'<li>Замените их эквивалентными резисторами.</li>',
'<li>Сложите последовательные сопротивления.</li>',
'</ol>',
'`,
'].join('\n');

const newRus = [
'      theory: `## Правописание союзов',
'',
'Союзы звучат так же, как местоимения с частицами, но пишутся по-разному. «Чтобы» и «что бы» произносятся одинаково, а пишутся по-разному.',
'',
'---',
'',
'### ЧТОБЫ (союз цели)',
'',
'<strong>Слитно:</strong> союз <strong>чтобы</strong> (= для того чтобы).',
'<p><em>Я пришёл, <strong>чтобы</strong> помочь.</em></p>',
'',
'<strong>Раздельно:</strong> местоимение <strong>что</strong> + частица <strong>бы</strong> (бы можно убрать/переставить).',
'<p><em>Что бы мне сделать?</em> (Что мне сделать бы?)</p>',
'',
'<div class="theory-warning">',
'<strong>Проверка:</strong> Если «бы» можно убрать → раздельно. Нельзя → слитно.',
'</div>',
'',
'---',
'',
'### ТОЖЕ / ТАКЖЕ (= и)',
'',
'<strong>Слитно:</strong> <strong>тоже, также</strong> (= <strong>и</strong>).',
'<p><em>Он <strong>тоже</strong> пришёл. (= И он пришёл.)</em></p>',
'',
'<strong>Раздельно:</strong>',
'<p><strong>то же</strong> (же можно опустить): <em>Он сказал <strong>то же</strong> самое.</em></p>',
'<p><strong>так же</strong> (же можно опустить): <em>Он сделал <strong>так же</strong>, как я.</em></p>',
'',
'---',
'',
'### ЗАТО (= НО)',
'',
'<strong>Слитно:</strong> <strong>зато</strong> (= но). <em>Дорого, <strong>зато</strong> качественно.</em>',
'<strong>Раздельно:</strong> предлог <strong>за</strong> + местоимение <strong>то</strong>. <em>Спрячься <strong>за то</strong> дерево.</em>',
'',
'---',
'',
'### Подчинительные союзы (всегда раздельно)',
'',
'потому что, оттого что, так как, для того чтобы, так что, в то время как, после того как',
'`,
'].join('\n');

const result = [...lines.slice(0, physStart), newPhys, ...lines.slice(physEnd + 1, rusStart), newRus, ...lines.slice(rusEnd + 1)].join('\n');
fs.writeFileSync(filePath, result);
console.log('Day 27 expanded');
