const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'src', 'content', 'week-01', 'day-05.ts');
let content = fs.readFileSync(filePath, 'utf8');
const lines = content.split('\n');

// Find theory backtick start and end lines
let theoryStarts = [];
let theoryEnds = [];
for (let i = 0; i < lines.length; i++) {
  if (lines[i].includes('theory: `') && !lines[i].trim().startsWith('//')) {
    theoryStarts.push(i);
  }
}
for (let i = 0; i < lines.length; i++) {
  if (lines[i].trim() === '`,' && theoryStarts.some(s => i > s)) {
    theoryEnds.push(i);
  }
}

console.log('Starts:', theoryStarts, 'Ends:', theoryEnds);
const mathStart = theoryStarts[0];
const mathEnd = theoryEnds[0];
const chemStart = theoryStarts[1];
const chemEnd = theoryEnds[1];

const newMathTheory = [
  '      theory: `## Пропорции и отношения',
  '',
  'Пропорции окружают нас повсюду: соотношение ингредиентов в рецепте, масштаб карты, смешивание растворов.',
  '',
  '---',
  '',
  '### Отношение чисел',
  '',
  '<div class="theory-definition">',
  '<strong>Отношение</strong> чисел $a$ и $b$ — это их частное: $a : b$ или $\frac{a}{b}$.',
  '</div>',
  '',
  'Отношение показывает, **во сколько раз** первое число больше второго (если $a > b$) или **какую часть** первое число составляет от второго (если $a < b$).',
  '',
  '<div class="theory-example">',
  '<strong>Пример 1:</strong> Отношение 3 : 5 = 3/5 = 0.6. Первое число = 0.6 (60%) второго.',
  '<p><strong>Пример 2:</strong> Отношение 8 : 2 = 4. Первое число в 4 раза больше второго.</p>',
  '</div>',
  '',
  '---',
  '',
  '### Пропорция',
  '',
  '<div class="theory-definition">',
  '<strong>Пропорция</strong> — равенство двух отношений: $$a : b = c : d$$',
  '</div>',
  '',
  '- $a$ и $d$ — <strong>крайние</strong> члены',
  '- $b$ и $c$ — <strong>средние</strong> члены',
  '',
  '<div class="theory-formula">',
  '<strong>Основное свойство:</strong> произведение крайних членов = произведению средних.',
  '$$a \cdot d = b \cdot c$$',
  '</div>',
  '',
  '<div class="theory-example">',
  '<strong>Задача:</strong> Найдите $x$: $x : 6 = 4 : 3$.',
  '<p><strong>Решение:</strong> $3x = 24$, $x = 8$.</p>',
  '</div>',
  '',
  '<div class="theory-example">',
  '<strong>Задача:</strong> Найдите $x$: $\frac{12}{x} = \frac{3}{5}$.',
  '<p><strong>Решение:</strong> $60 = 3x$, $x = 20$.</p>',
  '</div>',
  '',
  '---',
  '',
  '### Прямая и обратная пропорциональность',
  '',
  '<div class="theory-definition">',
  '<strong>Прямая:</strong> при увеличении одной величины другая увеличивается во столько же раз.',
  '</div>',
  '',
  '<div class="theory-formula">$$\frac{x_1}{x_2} = \frac{y_1}{y_2}$$</div>',
  '',
  '<div class="theory-definition">',
  '<strong>Обратная:</strong> при увеличении одной величины другая уменьшается во столько же раз.',
  '</div>',
  '',
  '<div class="theory-formula">$$\frac{x_1}{x_2} = \frac{y_2}{y_1}$$</div>',
  '',
  '<div class="theory-example">',
  '<strong>Прямая:</strong> 3 кг яблок = 150 руб. Сколько стоят 5 кг?',
  '<p>$\frac{3}{5} = \frac{150}{x}$, $x = 250$ руб.</p>',
  '</div>',
  '',
  '<div class="theory-example">',
  '<strong>Обратная:</strong> 4 рабочих = 9 дней. Сколько дней нужно 6 рабочим?',
  '<p>$\frac{4}{6} = \frac{x}{9}$, $x = 6$ дней.</p>',
  '</div>',
  '',
  '<div class="theory-warning">',
  '<strong>Как не перепутать:</strong> Обе растут → прямая. Одна растёт, другая падает → обратная.',
  '</div>',
  '',
  '---',
  '',
  '### Деление числа в отношении',
  '',
  '<div class="theory-formula">$$\frac{a}{a+b} \cdot N, \quad \frac{b}{a+b} \cdot N$$</div>',
  '',
  '<div class="theory-example">',
  '<strong>Задача:</strong> Разделите 60 в отношении 2 : 3.',
  '<p>$2+3=5$ частей. $60/5=12$ на часть. $2\cdot12=24$, $3\cdot12=36$.</p>',
  '</div>',
  '',
  '---',
  '',
  '### Масштаб',
  '',
  '<div class="theory-definition">',
  '<strong>Масштаб</strong> — отношение длины на карте к реальной длине.',
  '</div>',
  '',
  '<div class="theory-example">',
  'Масштаб $1 : 100000$: 1 см на карте = 100000 см = 1 км.',
  '</div>',
  '',
  '<div class="theory-example">',
  '<strong>Задача:</strong> На карте $1:500000$ расстояние 8 см. Реальное расстояние?',
  '<p>1 см = 5 км. $8 \cdot 5 = 40$ км.</p>',
  '</div>',
  '`,',
].join('\n');

const newChemTheory = [
  '      theory: `## Химические элементы и знаки',
  '',
  'Всё вокруг — воздух, вода, предметы — состоит из химических элементов. Их около 120.',
  '',
  '---',
  '',
  '### Химический элемент',
  '',
  '<div class="theory-definition">',
  '<strong>Химический элемент</strong> — вид атомов с определённым зарядом ядра.',
  '</div>',
  '',
  'Заряд ядра = числу протонов = порядковому номеру в таблице Менделеева.',
  '',
  '---',
  '',
  '### Символы элементов',
  '',
  'Каждый элемент имеет символ (1-2 буквы). Первая — <strong>заглавная</strong>, вторая — <strong>строчная</strong>.',
  '',
  '<table>',
  '<thead><tr><th>Символ</th><th>Название</th></tr></thead>',
  '<tbody>',
  '<tr><td>H</td><td>Водород</td></tr>',
  '<tr><td>O</td><td>Кислород</td></tr>',
  '<tr><td>C</td><td>Углерод</td></tr>',
  '<tr><td>N</td><td>Азот</td></tr>',
  '<tr><td>Fe</td><td>Железо</td></tr>',
  '<tr><td>Cu</td><td>Медь</td></tr>',
  '<tr><td>Na</td><td>Натрий</td></tr>',
  '<tr><td>Cl</td><td>Хлор</td></tr>',
  '</tbody>',
  '</table>',
  '',
  '---',
  '',
  '### Химические формулы',
  '',
  '<div class="theory-definition">',
  '<strong>Индекс</strong> — число атомов в молекуле. <strong>Коэффициент</strong> — число молекул.',
  '</div>',
  '',
  '<div class="theory-example">',
  '$H_2O$: 2 атома H, 1 атом O. $2H_2O$: 4 атома H, 2 атома O.',
  '</div>',
  '',
  '---',
  '',
  '### Простые и сложные вещества',
  '',
  '<table>',
  '<thead><tr><th>Простые (1 элемент)</th><th>Сложные (2+ элементов)</th></tr></thead>',
  '<tbody>',
  '<tr><td>$O_2$, $H_2$, $Fe$, $S$</td><td>$H_2O$, $CO_2$, $NaCl$</td></tr>',
  '</tbody>',
  '</table>',
  '`,',
].join('\n');

const result = [
  ...lines.slice(0, mathStart),
  newMathTheory,
  ...lines.slice(mathEnd + 1, chemStart),
  newChemTheory,
  ...lines.slice(chemEnd + 1),
].join('\n');

fs.writeFileSync(filePath, result);
console.log('Done. Math theory lines:', newMathTheory.split('\n').length, 'Chem theory lines:', newChemTheory.split('\n').length);
